# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4aa483170bec8a1892150888e88512dab7ade068196a4834938f0c527c29e6be3913d5a67da94d471213c402452d8c21b77ab27e48802c206ca9885d2280b45e

test:
  secret_key_base: 7f9b6ae1d9bd27192fb9f2fa686cb2f540d1ddaf3500ce644794766165a6e89f99d69ca8004390b1b2fa901119aeffac5e2bce23f6b56675edffa760ebfae3d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
